# Generated by Django 3.2.7 on 2021-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-num_recipes'], 'permissions': (('can_mark_blocked', 'Set recipe or author as blocked'),)},
        ),
        migrations.AddField(
            model_name='author',
            name='num_recipes',
            field=models.CharField(default=0, editable=False, max_length=3),
        ),
    ]
