# Generated by Django 3.2.7 on 2021-10-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211002_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='num_recipes',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
